version: "3.6"
services:
  rabbitmq3:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=pavel_test
      - RABBITMQ_DEFAULT_PASS=pavel_test
    networks:
      - pika
    ports:
      - 15672:15672
      - 5672:5672
      - 5671:5671

